'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EvoHtmlToPdfDemo.HTML_to_PDF


	Partial Public Class Display_Session_Variables

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' firstNameLabel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected firstNameLabel As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' lastNameLabel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected lastNameLabel As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' genderLabel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected genderLabel As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' haveCarLabel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected haveCarLabel As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' carTypePanel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected carTypePanel As Global.System.Web.UI.WebControls.Panel

		''' <summary>
		''' carTypeLabel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected carTypeLabel As Global.System.Web.UI.WebControls.Label

		''' <summary>
		''' commentsLabel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected commentsLabel As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
