'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EvoHtmlToPdfDemo.HTML_to_PDF


	Partial Public Class Getting_Started

		''' <summary>
		''' demoMenu control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMenu As Global.System.Web.UI.WebControls.Menu

		''' <summary>
		''' demoMultiView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMultiView As Global.System.Web.UI.WebControls.MultiView

		''' <summary>
		''' liveDemoView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected liveDemoView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' convertUrlRadioButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected convertUrlRadioButton As Global.System.Web.UI.WebControls.RadioButton

		''' <summary>
		''' convertHtmlRadioButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected convertHtmlRadioButton As Global.System.Web.UI.WebControls.RadioButton

		''' <summary>
		''' urlPanel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected urlPanel As Global.System.Web.UI.WebControls.Panel

		''' <summary>
		''' urlTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected urlTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' htmlStringPanel control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected htmlStringPanel As Global.System.Web.UI.WebControls.Panel

		''' <summary>
		''' htmlStringTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected htmlStringTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' baseUrlTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected baseUrlTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' htmlViewerWidthTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected htmlViewerWidthTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' htmlViewerHeightTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected htmlViewerHeightTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' pdfPageSizeDropDownList control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pdfPageSizeDropDownList As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' pdfPageOrientationDropDownList control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pdfPageOrientationDropDownList As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' navigationTimeoutTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected navigationTimeoutTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' conversionDelayTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected conversionDelayTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' openInlineCheckBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected openInlineCheckBox As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' convertToPdfButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected convertToPdfButton As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' descriptionView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' descriptionLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' sampleCodeView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' sampleCodeLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' Master property.
		''' </summary>
		''' <remarks>
		''' Auto-generated property.
		''' </remarks>
		Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
			Get
				Return (CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage))
			End Get
		End Property
	End Class
End Namespace
