'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EvoHtmlToPdfDemo.PDF_Creator


	Partial Public Class Create_PDF_Documents

		''' <summary>
		''' demoMenu control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMenu As Global.System.Web.UI.WebControls.Menu

		''' <summary>
		''' demoMultiView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMultiView As Global.System.Web.UI.WebControls.MultiView

		''' <summary>
		''' liveDemoView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected liveDemoView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' fullPdfRadioButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected fullPdfRadioButton As Global.System.Web.UI.WebControls.RadioButton

		''' <summary>
		''' pdfARadioButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pdfARadioButton As Global.System.Web.UI.WebControls.RadioButton

		''' <summary>
		''' pdfXRadioButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pdfXRadioButton As Global.System.Web.UI.WebControls.RadioButton

		''' <summary>
		''' rgbRadioButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected rgbRadioButton As Global.System.Web.UI.WebControls.RadioButton

		''' <summary>
		''' grayScaleRadioButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected grayScaleRadioButton As Global.System.Web.UI.WebControls.RadioButton

		''' <summary>
		''' cmykRadioButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cmykRadioButton As Global.System.Web.UI.WebControls.RadioButton

		''' <summary>
		''' pdfPageSizeDropDownList control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pdfPageSizeDropDownList As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' pdfPageOrientationDropDownList control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected pdfPageOrientationDropDownList As Global.System.Web.UI.WebControls.DropDownList

		''' <summary>
		''' leftMarginTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected leftMarginTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' rightMarginTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected rightMarginTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' topMarginTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected topMarginTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' bottomMarginTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected bottomMarginTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' createPdfButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected createPdfButton As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' descriptionView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' descriptionLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' sampleCodeView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' sampleCodeLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' Master property.
		''' </summary>
		''' <remarks>
		''' Auto-generated property.
		''' </remarks>
		Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
			Get
				Return (CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage))
			End Get
		End Property
	End Class
End Namespace
