'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EvoHtmlToPdfDemo.HTML_to_PDF.HTML_to_Image_Elements

    Partial Public Class Add_HTML_to_Image_Elements_to_PDF

        '''<summary>
        '''demoMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents demoMenu As Global.System.Web.UI.WebControls.Menu

        '''<summary>
        '''demoMultiView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents demoMultiView As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''liveDemoView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liveDemoView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''urlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''htmlViewerWidthTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents htmlViewerWidthTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''htmlViewerHeightTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents htmlViewerHeightTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''clipContentCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents clipContentCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''xLocationTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents xLocationTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''yLocationTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents yLocationTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''contentWidthTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents contentWidthTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''contentHeightTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents contentHeightTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''convertToPdfButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents convertToPdfButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''descriptionView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''descriptionLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''sampleCodeView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sampleCodeView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sampleCodeLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
            Get
                Return CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage)
            End Get
        End Property
    End Class
End Namespace
