'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EvoHtmlToPdfDemo.HTML_to_PDF.HTTP_Headers_and_Cookies


	Partial Public Class Add_Cookies_to_Request

		''' <summary>
		''' demoMenu control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMenu As Global.System.Web.UI.WebControls.Menu

		''' <summary>
		''' demoMultiView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMultiView As Global.System.Web.UI.WebControls.MultiView

		''' <summary>
		''' liveDemoView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected liveDemoView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' urlTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected urlTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie1NameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie1NameTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie1ValueTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie1ValueTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie2NameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie2NameTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie2ValueTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie2ValueTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie3NameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie3NameTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie3ValueTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie3ValueTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie4NameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie4NameTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie4ValueTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie4ValueTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie5NameTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie5NameTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' cookie5ValueTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected cookie5ValueTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' convertToPdfButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected convertToPdfButton As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' descriptionView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' descriptionLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' sampleCodeView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' sampleCodeLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' Master property.
		''' </summary>
		''' <remarks>
		''' Auto-generated property.
		''' </remarks>
		Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
			Get
				Return (CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage))
			End Get
		End Property
	End Class
End Namespace
