'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EvoHtmlToPdfDemo.PDF_Creator.Headers_and_Footers

    Partial Public Class Header_Footer_Change

        '''<summary>
        '''demoMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents demoMenu As Global.System.Web.UI.WebControls.Menu

        '''<summary>
        '''demoMultiView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents demoMultiView As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''liveDemoView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liveDemoView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''urlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''changeHeaderAndFooterCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents changeHeaderAndFooterCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''createPdfButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents createPdfButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''descriptionView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''descriptionLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''sampleCodeView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sampleCodeView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sampleCodeLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
            Get
                Return CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage)
            End Get
        End Property
    End Class
End Namespace
