'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EvoHtmlToPdfDemo.HTML_to_PDF.Watermarks_Stamps

    Partial Public Class Add_Watermarks_Stamps

        '''<summary>
        '''demoMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents demoMenu As Global.System.Web.UI.WebControls.Menu

        '''<summary>
        '''demoMultiView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents demoMultiView As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''liveDemoView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liveDemoView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''urlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents urlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''stampWidthTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stampWidthTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''stampHeightTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents stampHeightTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''htmlStringTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents htmlStringTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''baseUrlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents baseUrlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''convertToPdfButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents convertToPdfButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''descriptionView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''descriptionLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''sampleCodeView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sampleCodeView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sampleCodeLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
            Get
                Return CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage)
            End Get
        End Property
    End Class
End Namespace
