'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EvoHtmlToPdfDemo.HTML_to_PDF.Bookmarks


	Partial Public Class Auto_Create_Bookmarks

		''' <summary>
		''' demoMenu control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMenu As Global.System.Web.UI.WebControls.Menu

		''' <summary>
		''' demoMultiView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMultiView As Global.System.Web.UI.WebControls.MultiView

		''' <summary>
		''' liveDemoView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected liveDemoView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' urlTextBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected urlTextBox As Global.System.Web.UI.WebControls.TextBox

		''' <summary>
		''' autoBookmarksCheckBox control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected autoBookmarksCheckBox As Global.System.Web.UI.WebControls.CheckBox

		''' <summary>
		''' convertToPdfButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected convertToPdfButton As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' descriptionView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' descriptionLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' sampleCodeView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' sampleCodeLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' Master property.
		''' </summary>
		''' <remarks>
		''' Auto-generated property.
		''' </remarks>
		Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
			Get
				Return (CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage))
			End Get
		End Property
	End Class
End Namespace
