'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace EvoHtmlToPdfDemo.PDF_Editor


	Partial Public Class Merge_PDF

		''' <summary>
		''' demoMenu control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMenu As Global.System.Web.UI.WebControls.Menu

		''' <summary>
		''' demoMultiView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected demoMultiView As Global.System.Web.UI.WebControls.MultiView

		''' <summary>
		''' liveDemoView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected liveDemoView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' firstPdfFileHyperLink control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected firstPdfFileHyperLink As Global.System.Web.UI.WebControls.HyperLink

		''' <summary>
		''' secondPdfFileHyperLink control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected secondPdfFileHyperLink As Global.System.Web.UI.WebControls.HyperLink

		''' <summary>
		''' mergePdfButton control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected mergePdfButton As Global.System.Web.UI.WebControls.Button

		''' <summary>
		''' descriptionView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' descriptionLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected descriptionLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' sampleCodeView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeView As Global.System.Web.UI.WebControls.View

		''' <summary>
		''' sampleCodeLiteral control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

		''' <summary>
		''' Master property.
		''' </summary>
		''' <remarks>
		''' Auto-generated property.
		''' </remarks>
		Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
			Get
				Return (CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage))
			End Get
		End Property
	End Class
End Namespace
