'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EvoHtmlToPdfDemo.HTML_to_PDF.Headers_and_Footers

    Partial Public Class Header_Footer_on_Merged_HTML

        '''<summary>
        '''demoMenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents demoMenu As Global.System.Web.UI.WebControls.Menu

        '''<summary>
        '''demoMultiView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents demoMultiView As Global.System.Web.UI.WebControls.MultiView

        '''<summary>
        '''liveDemoView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents liveDemoView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''firstUrlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents firstUrlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''secondUrlTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents secondUrlTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''startNewPageCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents startNewPageCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''addHeaderCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addHeaderCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''addFooterCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addFooterCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''showHeaderInFirstPageCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents showHeaderInFirstPageCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''showHeaderInOddPagesCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents showHeaderInOddPagesCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''showHeaderInEvenPagesCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents showHeaderInEvenPagesCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''drawHeaderLineCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drawHeaderLineCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''headerSpacingTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents headerSpacingTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''firstPageSpacingTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents firstPageSpacingTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''showFooterInFirstPageCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents showFooterInFirstPageCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''showFooterInOddPagesCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents showFooterInOddPagesCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''showFooterInEvenPagesCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents showFooterInEvenPagesCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''addPageNumbersInFooterCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents addPageNumbersInFooterCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''drawFooterLineCheckBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents drawFooterLineCheckBox As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''footerSpacingTextBox control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents footerSpacingTextBox As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''convertToPdfButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents convertToPdfButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''descriptionView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''descriptionLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents descriptionLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''sampleCodeView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sampleCodeView As Global.System.Web.UI.WebControls.View

        '''<summary>
        '''sampleCodeLiteral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sampleCodeLiteral As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''Master property.
        '''</summary>
        '''<remarks>
        '''Auto-generated property.
        '''</remarks>
        Public Shadows ReadOnly Property Master() As EvoHtmlToPdfDemo.MasterPage
            Get
                Return CType(MyBase.Master, EvoHtmlToPdfDemo.MasterPage)
            End Get
        End Property
    End Class
End Namespace
